export const BOOK_LESSON = [
  { name: '1.រឿងសូផាត (ល្ខោននិយាយ)', key: 'cYuvU0r6htg' },
  { name: '2.រឿងផ្កាស្រពោន (ល្ខោននិយាយ)', key: 'PVVJ8GE1UbI' },
  { name: '3.រឿងមាលាដួងចិត្ត (១-២៩) / សង្ខេបរឿង', key: 'G-vWe83mkqw' },
  { name: '4.រឿងកុលាបប៉ៃលិន (ល្ខោននិយាយ)', key: 'ReLp3etDbmI' },
  { name: '5.រឿងធនញ្ជ័យ', key: 'KHlxmfrpMAU' },
  { name: '6.រឿងគូលីកំនែន', key: 'Hl_IIsYSEXA' },
  { name: '7.រឿងភូមិតិរិច្ឆាន', key: 'kJ-EAbskFhU' },
  { name: '8.រឿងគ្រូបង្រៀនស្រុកស្រែ', key: 'lAQZqLhIhi4' },
  { name: '9.រឿងមហាចោរទល់ដែន', key: '61oBpUlmlPs' },
  { name: '10.រឿងពុទ្ធិសែន នាងកង្រី', key: 'Db_cVwRHeLY' },
  { name: '11.រឿងរាមកេរ្ដិ៍', key: 'o9MNXX_jlJ8' },
  { name: '12.រឿងទុំទាវ', key: 'e5RoNzKHcV8' },
  { name: '13.រឿងហង្សយន្ដ', key: 'IEktenkeFhU' },
  { name: '14.រឿងចៅស្រទបចេក', key: 'QqzCDU10UrU' },
  { name: '15.រឿងកាកី', key: '1L5zHjUkuvk' },
  { name: '15.រឿងថៅកែចិត្តចោរ', key: '9CzU6gJFyEg' },
];
